app:
  name: "AliangRest"
  host: "http://localhost"
  port: 8888
  env: "development"  # 环境 development / production
  debug: true         # 是否开启调试模式

database:
  driver: "mysql"            # 数据库类型（mysql, postgres, sqlite）
  host: "localhost"
  port: 3306
  user: "root"
  password: "111111"
  name: "rest"
  max_open_conns: 50         # 最大连接数
  max_idle_conns: 10         # 最大空闲连接数
  log_level: "debug"         # SQL 日志级别（silent, error, warn, info, debug）
  show_sql: true             # 是否展示 SQL 语句

redis:
  host: "127.0.0.1"
  port: 6379
  db: 0
  password: ""

jwt:
  secret: "my_secret_key"
  expires_in: 86400   # JWT 过期时间（秒）

log:
  level: "debug"      # 日志级别（debug, info, warn, error, fatal）
  file: "logs/app.log" # 日志文件路径
  max_size: 10        # 日志文件最大大小（MB）
  max_backups: 3      # 最多保留的旧日志文件数
  max_age: 7         # 日志最长保留天数
